server:
  port: ${PORT:8080}
  servlet:
    session:
      cookie:
        secure: true

logging:
  level:
    org:
      atmosphere: warn

spring:
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: bc1be8d7831e71f84180
            # Attention. A GitHub app can just have one redirect-uri only configured!
            #redirect-uri: https://dbapi-dot-simulation-sample.ey.r.appspot.com/login/oauth2/code/github
            redirect-uri: https://samplegae.com/login/oauth2/code/github #Domain registered under: https://domains.google.com/
            #redirect-uri: http://localhost:8080/login/oauth2/code/github
          dbApi:
            client-name: HolgersTestAppPkce
            client-id: 2f5d1360-0938-4ef5-a006-118dbf38cb68
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            #redirect-uri: https://dbapi-dot-simulation-sample.ey.r.appspot.com/login/oauth2/code/github
            redirect-uri: https://samplegae.com/login/oauth2/code/dbApi #Domain registered under: https://domains.google.com/
            #redirect-uri: http://localhost:8080/login/oauth2/code/dbApi
            scope: offline_access,openid,read_accounts,read_transactions,read_addresses
        provider:
          dbApi:
            authorization-uri: https://simulator-api.db.com/gw/oidc/authorize
            token-uri: https://simulator-api.db.com/gw/oidc/token
            user-info-uri: https://simulator-api.db.com/gw/oidc/userinfo
            jwk-set-uri: https://simulator-api.db.com/gw/oidc/jwk
            issuer-uri: https://simulator-api.db.com/gw/oidc/
  mustache:
    check-template-location: false
  cloud:
      gcp:
        kms:
          project-id: simulation-sample
          location-id: europe-west3
          key-ring-id: simulation-sample-keyring
          key-id: simulation-sample-keyname
        storage:
          bucket-name: client-credentials-bucket

# Launch the default browser when starting the application in development mode
vaadin:
  launch-browser: true
  # To improve the performance during development.
  # For more information https://vaadin.com/docs/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
  .whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.example.application

dbApi:
  url:
    cashAccounts: https://simulator-api.db.com/gw/dbapi/banking/cashAccounts/v2
    cashAccountTransactions: https://simulator-api.db.com/gw/dbapi/banking/transactions/v2/
    addresses: https://simulator-api.db.com/gw/dbapi/referenceData/addresses/v2
