#Attention - don't rename this file. Otherwise, GAE can't be deployed correctly!
runtime: java11
env: standard
instance_class: F2

automatic_scaling:
  max_instances: 1
  min_instances: 0
  min_idle_instances: 0
  max_idle_instances: 1

handlers:
  - url: /.*
    script: this field is required, but ignored
